### ISSUE TITLE
Problems on win7

### ISSUE THREAD

**Issue by mlcampbe** [TaylorSMarks/playsound#8] opened 2017-06-13 15:03 UTC
When trying to use the modules on windows I am getting the following error when attempting to play a wav or mp3 file. Any ideas?

Traceback (most recent call last):
  File "a.py", line 2, in <module>
    playsound('success.wav')
  File "C:\Python35\lib\site-packages\playsound.py", line 37, in _playsoundWin
    winCommand('play', alias, 'from 0 to', durationInMS)
  File "C:\Python35\lib\site-packages\playsound.py", line 22, in winCommand
    command = ' '.join(command).encode()
TypeError: sequence item 3: expected str instance, bytes found

**Comment by TaylorSMarks** [comment] 2017-06-13 15:14
This is a duplicate of #2 . You can get the latest code with that fixed by installing straight from github instead of via pypi. 

Eventually I need to figure out how to update the version that's on pypi...

**Closed by TaylorSMarks** 2017-06-13 15:14 UTC

**Comment by mlcampbe** [comment] 2017-06-13 15:24
Thanks that took care of it.

Note I did look at the issues before reporting this but I didn't see the old comments for some reason. Sorry to waste your time.
