### ISSUE TITLE
unicodeerror on windows 10 

### ISSUE THREAD

**Issue by fcouloigner** [TaylorSMarks/playsound#29] opened 2019-04-15 14:20 UTC
screencopy (windows  10) :

C:\Users\Public>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from playsound import playsound
>>> playsound('nougayork.mp3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\brigitte and co\AppData\Roaming\Python\Python36\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
  File "C:\Users\brigitte and co\AppData\Roaming\Python\Python36\site-packages\playsound.py", line 30, in winCommand
    '\n    ' + errorBuffer.value.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 8: invalid continuation byte
>>>

**Comment by fawnsans** [comment] 2019-06-09 12:27
same

**Comment by insolor** [comment] 2019-06-10 17:18
The problem occurs when you have non-ascii characters in the path to the file. 

Quick fix (not tested yet):

```
def winCommand(*command):
    buf = c_buffer(512)
    command = ' '.join(command).encode('utf-16')
    errorCode = int(windll.winmm.mciSendStringW(command, buf, 511, 0))
    if errorCode:
        errorBuffer = c_buffer(512)
        windll.winmm.mciGetErrorStringW(errorCode, errorBuffer, 511)
        exceptionMessage = ('\n    Error ' + str(errorCode) + ' for command:'
                            '\n        ' + command +
                            '\n    ' + errorBuffer.value.decode('utf-16'))
        raise PlaysoundException(exceptionMessage)
    return buf.value
```

**Comment by insolor** [comment] 2019-06-12 15:09
After some testing and more fixes, `_playsoundWin` looks like this

```
def _playsoundWin(sound, block = True):
    '''
    snip
    '''
    from ctypes import c_buffer, windll
    from random import random
    from time   import sleep
    from sys    import getfilesystemencoding

    def winCommand(*command):
        buf = c_buffer(512)
        command = ' '.join(command)
        errorCode = int(windll.winmm.mciSendStringW(command.encode('utf-16'), buf, 511, 0))
        if errorCode:
            errorBuffer = c_buffer(512)
            windll.winmm.mciGetErrorStringW(errorCode, errorBuffer, 511)
            exceptionMessage = ('\n    Error ' + str(errorCode) + ' for command:'
                                '\n        ' + command +
                                '\n    ' + errorBuffer.raw.decode('utf-16').rstrip('\0'))
            raise PlaysoundException(exceptionMessage)
        return buf.raw.decode('utf-16').rstrip('\0')

    alias = 'playsound_' + str(random())
    winCommand('open "' + sound + '" alias', alias)
    winCommand('set', alias, 'time format milliseconds')
    durationInMS = winCommand('status', alias, 'length')
    winCommand('play', alias, 'from 0 to', durationInMS)

    if block:
        sleep(float(durationInMS) / 1000.0)
```

**Comment by ClericPy** [comment] 2019-08-03 11:26
So here need one prompt encoding arg to avoid encode error, not only utf-16, I need gbk too...

**Comment by insolor** [comment] 2019-08-03 11:31
@ClericPy if UTF-16 is not enough for Chinese then yes, it needs another encoding argument.

**Comment by Danixu** [comment] 2019-08-18 20:36
Hello!!,

Is there any plan to apply the fix in main branch?

Thanks!

**Comment by TaylorSMarks** [comment] 2019-08-18 20:39
No.

The reason why is because I don’t care. pip can install straight from a git url - use that if you want to get the version off this branch.

Taylor

**Comment by Danixu** [comment] 2019-08-18 21:50
I see... the solution is there and you don't have to work, but is too hard to do it. You've lost more time writting the message than the one you need to merfe, but is better to do an unfriendly response.

Anyway, thanks to Insolor, your code works fine on Windows 10 and using paths with accents. I had to change two lines, but almost all was done. Later I'll see all forks because I've seen interesting things.

Greetings!!

**Comment by TaylorSMarks** [comment] 2019-08-18 22:20
I used to accept the patches/pull requests, but as you yourself just pointed out, you needed to modify two lines for it to work. I’ve found it’s a game of whack-a-mole - you accept one and suddenly there’s more people complaining about bugs introduced by the latest patch. It’s easier to just ignore all the complaints.

If I was getting paid for it, maybe I’d put more effort in. As is, I’m not.

If Unicode isn’t working, why not rename your files? Really, a higher priority for me with this (so low priority that I’ll also probably never do it) would be making it work on a Raspberry Pi.

Taylor

**Comment by XHG78999** [comment] 2020-01-22 02:28
> 经过一些测试和更多修复后，`_playsoundWin`看起来像这样
> 
> ```
> def _playsoundWin(sound, block = True):
>     '''
>     snip
>     '''
>     from ctypes import c_buffer, windll
>     from random import random
>     from time   import sleep
>     from sys    import getfilesystemencoding
> 
>     def winCommand(*command):
>         buf = c_buffer(512)
>         command = ' '.join(command)
>         errorCode = int(windll.winmm.mciSendStringW(command.encode('utf-16'), buf, 511, 0))
>         if errorCode:
>             errorBuffer = c_buffer(512)
>             windll.winmm.mciGetErrorStringW(errorCode, errorBuffer, 511)
>             exceptionMessage = ('\n    Error ' + str(errorCode) + ' for command:'
>                                 '\n        ' + command +
>                                 '\n    ' + errorBuffer.raw.decode('utf-16').rstrip('\0'))
>             raise PlaysoundException(exceptionMessage)
>         return buf.raw.decode('utf-16').rstrip('\0')
> 
>     alias = 'playsound_' + str(random())
>     winCommand('open "' + sound + '" alias', alias)
>     winCommand('set', alias, 'time format milliseconds')
>     durationInMS = winCommand('status', alias, 'length')
>     winCommand('play', alias, 'from 0 to', durationInMS)
> 
>     if block:
>         sleep(float(durationInMS) / 1000.0)
> ```

Question: Can't use locale.getpreferredencoding () function? (See Fluiano Python for Luciano Ramalho for this function)

**Comment by insolor** [comment] 2020-01-22 05:05
> Can't use locale.getpreferredencoding () function?

Probably yes, but I'm not very interested in the further improvement of the patch. You can try yourself.

**Comment by XHG78999** [comment] 2020-01-28 08:28
> > 无法使用locale.getpreferredencoding（）函数？
> 
> 可能是的，但是我对补丁的进一步改进不是很感兴趣。您可以尝试一下。

经过我测试，结果出现的错误里冒出了乱码。(Sorry,it is Chinese.I don't have any time to translate it.You can translate it.)

**Comment by XHG78999** [comment] 2020-01-29 03:39
Now, I solved the problem. On my Windows 10, the modified playsound.py successfully played music with a Chinese path. Now, I will attach this file code, please trouble me to push it for me.
(The focus is actually on Wincommand instructions, not Python code.)

`def _playsoundWin(sound, block = True):
    '''
    Utilizes windll.winmm. Tested and known to work with MP3 and WAVE on
    Windows 7 with Python 2.7. Probably works with more file formats.
    Probably works on Windows XP thru Windows 10. Probably works with all
    versions of Python.
    Inspired by (but not copied from) Michael Gundlach <gundlach@gmail.com>'s mp3play:
    https://github.com/michaelgundlach/mp3play
    I never would have tried using windll.winmm without seeing his code.
    '''
    from ctypes import c_buffer, windll
    from random import randint
    from time   import sleep
    from sys    import getfilesystemencoding
    #from locale import getpreferredencoding

    def winCommand(*command):
        buf = c_buffer(512)
        encoding=getfilesystemencoding()
        command = ' '.join(command).encode('utf-16')
        #command = ' '.join(command).encode(encoding)
        errorCode = int(windll.winmm.mciSendStringW(command, buf, 511, 0))  # use widestring version of the function
        if errorCode:
            errorBuffer = c_buffer(512)
            windll.winmm.mciGetErrorStringW(errorCode, errorBuffer, 511)  # use widestring version of the function
            exceptionMessage = ('\n    Error ' + str(errorCode) + ' for command:'
                                '\n        ' + command.decode('utf-16') +
                                #'\n        ' + command.decode(encoding) +
                                '\n    ' + errorBuffer.value.decode('utf-16'))
                                #'\n    ' + errorBuffer.value.decode(encoding))
            raise PlaysoundException(exceptionMessage)
        return buf.value

    #alias = 'playsound_' + str(randint(1,1000))
    winCommand('open "' + sound +'"')#+ '" alias', alias)
    #winCommand('set', alias, 'time format milliseconds')
    durationInMS = winCommand('status', sound, 'length')
    winCommand('play', sound)#, 'from 0 to', durationInMS.decode())
    #winCommand("play",sound)

    if block:
        sleep(float(durationInMS)*15)`

**Comment by Remi-Avec-Un-I** [comment] 2021-06-16 10:12
> 
> 
> I see... the solution is there and you don't have to work, but is too hard to do it. You've lost more time writting the message than the one you need to merge, but is better to do an unfriendly response.
> 
> Anyway, thanks to Insolor, your code works fine on Windows 10 and using paths with accents. I had to change two lines, but almost all was done. Later I'll see all forks because I've seen interesting things.
> 
> Greetings!!

Hey, i didn't understand how are we suppose to fix it, can you help me ?

**Comment by TaylorSMarks** [comment] 2021-07-15 00:56
This should be fixed on master now. The testcase testBlockingCYRIL_WAV should ensure that regressions don't occur.

I'll try to upload what's on master to Pypi in the next day or two.

**Closed by TaylorSMarks** 2021-07-15 00:56 UTC
